services:
  pgdatabase:
    image: postgres:13
    # restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    # restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80" 

# [winpty] docker-compose up
# Shut it down with `winpty docker-compose down`
# Don't need to write the full path for the volumes
# Docker provides `restart` policies to control whether your containers start automatically when they exit, or when Docker restarts
#   - These that linked containers are started in the correct order
# The containers automatically become part of a network, so we don't have to specify it here