
version: 2

models:
  - name: dim_zones
    description: >
      List of unique zones identified by location_id. 
      Includes the service zone they correspond to (green or yellow).
    columns:
      - name: location_id
        data_type: numeric
        description: ""

      - name: borough
        data_type: string
        description: ""

      - name: zone
        data_type: string
        description: ""

      - name: service_zone
        data_type: string
        description: ""

  - name: dm_monthly_zone_revenue
    description: >
      Aggregated table of all taxi trips corresponding to both service zones (green and yellow) per pickup zone, month and service.
      The table contains monthly sums of the fare elements used to calculate the monthly revenue. 
      The table contains also monthly indicators like number of trips, and average trip distance. 
    columns:
      - name: revenue_zone
        data_type: string
        description: ""

      - name: revenue_month
        data_type: timestamp
        description: ""

      - name: service_type
        data_type: string
        description: The designator of if a ride was a Yellow or a Green taxi

      - name: revenue_monthly_fare
        data_type: numeric
        description: ""

      - name: revenue_monthly_extra
        data_type: numeric
        description: ""

      - name: revenue_monthly_mta_tax
        data_type: numeric
        description: ""

      - name: revenue_monthly_tip_amount
        data_type: numeric
        description: ""

      - name: revenue_monthly_tolls_amount
        data_type: numeric
        description: ""

      - name: revenue_monthly_improvement_surcharge
        data_type: numeric
        description: ""

      - name: revenue_monthly_total_amount
        data_type: numeric
        description: Monthly sum of the the total_amount of the fare charged for the trip per pickup zone, month and service.
        tests:
          - not_null:
              severity: error        

      - name: total_monthly_trips
        data_type: int64
        description: ""

      - name: avg_montly_passenger_count
        data_type: float64
        description: ""

      - name: avg_montly_trip_distance
        data_type: numeric
        description: ""

  - name: fact_trips
    description: >
      Taxi trips corresponding to both service zones (green and yellow).
      The table contains records where both pickup and dropoff locations are valid and known zones. 
      Each record corresponds to a trip uniquely identified by trip_id.
    columns:
      - name: trip_id
        data_type: string
        description: The primary key for this table, generated with a concatenation of vendor_id and pickup_datetime fields
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: vendor_id
        data_type: int64
        description: > 
          A code indicating the TPEP provider that provided the record.
          1= Creative Mobile Technologies, LLC; 
          2= VeriFone Inc.

      - name: service_type
        data_type: string
        description: The designator of if a ride was a Yellow or a Green taxi

      - name: rate_code_id
        data_type: int64
        description: >
          The final rate code in effect at the end of the trip.
            1=Standard rate
            2=JFK
            3=Newark
            4=Nassau or Westchester
            5=Negotiated fare
            6=Group ride

      - name: pickup_location_id
        data_type: int64
        description: The location_id where the meter was engaged.
        # check if this field is located in the zone lookup table
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: location_id
              severity: warn

      - name: pickup_borough
        data_type: string
        description: The bourough where the meter was engaged.

      - name: pickup_zone
        data_type: string
        description: The zone where the meter was engaged.

      - name: dropoff_location_id
        data_type: int64
        description: The location_id where the meter was disengaged.
        # check if this field is located in the zone lookup table
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: location_id
              severity: warn

      - name: dropoff_borough
        data_type: string
        description: The bourough where the meter was disengaged.

      - name: dropoff_zone
        data_type: string
        description: The zone where the meter was disengaged.

      - name: pickup_datetime
        data_type: timestamp
        description: The date and time when the meter was engaged.

      - name: dropoff_datetime
        data_type: timestamp
        description: The date and time when the meter was disengaged.

      - name: store_and_fwd_flag
        data_type: string
        description: > 
          This flag indicates whether the trip record was held in vehicle
          memory before sending to the vendor, aka “store and forward,”
          because the vehicle did not have a connection to the server.
            Y= store and forward trip
            N= not a store and forward trip

      - name: passenger_count
        data_type: int64
        description: The number of passengers in the vehicle. This is a driver-entered value.

      - name: trip_distance
        data_type: numeric
        description: The elapsed trip distance in miles reported by the taximeter.

      - name: trip_type
        data_type: int64
        description: A code indicating whether the trip was a street-hail or a dispatch that is automatically assigned based on the metered rate in use but can be overridden by the driver.

      - name: fare_amount
        data_type: numeric
        description: >
          The time-and-distance fare calculated by the meter.
          Extra Miscellaneous extras and surcharges. Currently, this only includes
          the $0.50 and $1 rush hour and overnight charges.
          MTA_tax $0.50 MTA tax that is automatically triggered based on the metered
          rate in use.

      - name: extra
        data_type: numeric
        description: Extra charges. Currently, this only includes the 0.5 dollars and 1 dollar rush hour and overnight charges.

      - name: mta_tax
        data_type: numeric
        description: The 0.50 dollars MTA tax that is automatically triggered based on the metered rate in use.

      - name: tip_amount
        data_type: numeric
        description: > 
          Tip amount. This field is automatically populated for credit card
          tips. Cash tips are not included.

      - name: tolls_amount
        data_type: numeric
        description: Total amount of all tolls paid in trip.

      - name: improvement_surcharge
        data_type: numeric
        description: > 
          $0.30 improvement surcharge assessed trips at the flag drop. The
          improvement surcharge began being levied in 2015.

      - name: total_amount
        data_type: numeric
        description: The total amount charged to passengers. Does not include cash tips.

      - name: payment_type
        data_type: int64
        description: A numeric code signifying how the passenger paid for the trip.

      - name: payment_type_description
        data_type: string
        description: Description of the payment_type code

      - name: congestion_surcharge
        data_type: numeric
        description: >
          2.75 dollars congestion surcharge assessed trips in yellow and green taxis in Manhattan south of 96th St. The surcharge began being levied in 2019.
